server:
  port: 8888
spring:
  elasticsearch:
    rest:
      connection-timeout: 30
      uris: localhost:9200
  application:
    name: API Service

config-prop:
  limitTime: 6000
  requestPerTime: 120
  tokensToConsume: 5
  keyHits: hits
  keySource: _source